services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: lab-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    command: ["/usr/sbin/mosquitto","-c","/mosquitto-no-auth.conf"]
    volumes:
      - type: volume
        source: mosquitto_data
        target: /mosquitto/data
      - type: volume
        source: mosquitto_log
        target: /mosquitto/log
volumes:
  mosquitto_data:
  mosquitto_log:
